package com.khapp.suji.utils

import com.khapp.suji.R

object IconSet {
    fun getIconSet(): Array<Int> {
        return arrayOf(R.mipmap.icon_preset_parking,
                R.mipmap.icon_preset_car_gas_station,
                R.mipmap.icon_preset_cloth_dress,
                R.mipmap.icon_preset_cloth_shirt,
                R.mipmap.icon_preset_digit_laptop,
                R.mipmap.icon_preset_digit_pc,
                R.mipmap.icon_preset_digit_phone,
                R.mipmap.icon_preset_drink_coffee,
                R.mipmap.icon_preset_drink_juice,
                R.mipmap.icon_preset_drink_normal,
                R.mipmap.icon_preset_drink_tea,
                R.mipmap.icon_preset_entertainment_movie,
                R.mipmap.icon_preset_entertainment,
                R.mipmap.icon_preset_fix,
                R.mipmap.icon_preset_food_bread,
                R.mipmap.icon_preset_food_chicken,
                R.mipmap.icon_preset_food_donut,
                R.mipmap.icon_preset_food_fried_rice,
                R.mipmap.icon_preset_food_grilled_meat,
                R.mipmap.icon_preset_food_omelette,
                R.mipmap.icon_preset_food_pizza,
                R.mipmap.icon_preset_food_steak,
                R.mipmap.icon_preset_food,
                R.mipmap.icon_preset_foof_rice,
                R.mipmap.icon_preset_foot_burger,
                R.mipmap.icon_preset_fruit_watermelon,
                R.mipmap.icon_preset_fruit,
                R.mipmap.icon_preset_furniture_drawers,
                R.mipmap.icon_preset_furniture_tv,
                R.mipmap.icon_preset_giftbox,
                R.mipmap.icon_preset_healthy_ambulance,
                R.mipmap.icon_preset_healthy_hospital,
                R.mipmap.icon_preset_healthy,
                R.mipmap.icon_preset_money_bill_2,
                R.mipmap.icon_preset_money_bill_3,
                R.mipmap.icon_preset_money_bill,
                R.mipmap.icon_preset_money_bussiness,
                R.mipmap.icon_preset_money_calendar,
                R.mipmap.icon_preset_money_creditcard,
                R.mipmap.icon_preset_money_envelop,
                R.mipmap.icon_preset_money_insurance,
                R.mipmap.icon_preset_money_investment,
                R.mipmap.icon_preset_money_payment,
                R.mipmap.icon_preset_money_redpack,
                R.mipmap.icon_preset_money_salary,
                R.mipmap.icon_preset_money_stocks,
                R.mipmap.icon_preset_money_transfer,
                R.mipmap.icon_preset_money,
                R.mipmap.icon_preset_placeholder,
                R.mipmap.icon_preset_shopping,
                R.mipmap.icon_preset_snack_chips,
                R.mipmap.icon_preset_snack_cookie,
                R.mipmap.icon_preset_snack_cookies,
                R.mipmap.icon_preset_snack_cupcake,
                R.mipmap.icon_preset_snack_donut,
                R.mipmap.icon_preset_snack_popcorn,
                R.mipmap.icon_preset_study_book,
                R.mipmap.icon_preset_supermarket,
                R.mipmap.icon_preset_transport_bike,
                R.mipmap.icon_preset_transport_car_2,
                R.mipmap.icon_preset_transport_car,
                R.mipmap.icon_preset_transport_plane,
                R.mipmap.icon_preset_transport_subway,
                R.mipmap.icon_preset_transport_taxi,
                R.mipmap.icon_preset_transport_train,
                R.mipmap.icon_preset_travelling)
    }
}